### ISSUE TITLE
MSVCP140D.dll Missing in 1.0 Version

### ISSUE THREAD

**Issue by IdahoSixString** [0x1mason/GribApi.NET#64]
Looks like the 1.0 beta version was compiled into the NuGet package as a debug package and not a release package. 

Can we get 1.0.1 as a release package?

This will result in an error on a machine that doesn't have Visual Studio installed.

System.TypeInitializationException: The type initializer for 'Grib.Api.GribFile' threw an exception. ---> System.Exception: Can't load DLL #####\Grib.Api\lib\win\x86\Grib.Api.Native.dll ---> System.ComponentModel.Win32Exception: The specified module could not be found
   --- End of inner exception stack trace ---
   at Grib.Api.Interop.Util.Win32.LoadWin32Library(String libPath) in **c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\Interop\Util\Win32.cs**:line 36
   at Grib.Api.GribEnvironmentLoadHelper.BootStrapLibrary() in **c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\GribEnvironmentLoadHelper.cs**:line 13
   at Grib.Api.GribEnvironment.Init() in **c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\GribEnvironment.cs**:line 64
   at Grib.Api.GribFile..cctor() in c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\GribFile.cs:line 45
   --- End of inner exception stack trace ---
   at Grib.Api.GribFile..ctor(String fileName)
   at ####ReadGribFile(FileInfo fileInfo, Boolean keepGeoSpacialData) in ####\DayAheadForecastJob.cs:line 517

Also yes this box does have the VCRedist 2015. (choco install vcredist2015)

Update - 6/27/2017

I feel I should update and clarify here. It is not specifically the .net solution that needs updating to be compiled in release but rather the Grib.Api.Native.dll that needs to be compiled in release and not debug.

**Comment by 0x1mason** [comment]
An interim workaround is to include MSVCP140D.dll as part of your app. Try adding it here `\Grib.Api\lib\win\x86\`, on `PATH`, or a well-known location.

**Comment by IdahoSixString** [comment]
@0x1mason While definitely not an ideal solution. It does work. However, I would highly recommend NOT doing this.

You will also need to add:
mfc140d.dll
mfcm140d.dll
msvcp140d.dll
msvcsr140d.dll
vcamp140d.dll
vccorlib140d.dll
vcomp140d.dll

**Comment by 0x1mason** [comment]
They don't make it easy, do they?

**Comment by IdahoSixString** [comment]
If it were easy I wouldn't have a job. :)

**Comment by IdahoSixString** [comment]
@0x1mason As a heads up the VC++ Redist 2013 will cover anyone whom has this issue. Unfortunately VC++ 2015 Redist version will not.

**Comment by 0x1mason** [comment]
Should be resolved by the new 1.0.0-beta2 I pushed up.

**Comment by IdahoSixString** [comment]
@0x1mason Just as a heads up. I have a new 2016 and the VC++ 2013 redis does not solve the problem with the latest you must use VC++ 2015 redis .
